packages:
  - 'backend'
  - 'frontend'

strictPeerDependencies: false
engineStrict: true
fetchTimeout: 300000
fetchRetries: 5
networkConcurrency: 4

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  prisma: true
