export type CreateHomePageRepoInput = {
  readonly heroTitle: string;
  readonly heroDescription: string;
  readonly heroImageMediaId: number | null;
  readonly primaryCtaText: string;
  readonly primaryCtaUrl: string;
  readonly secondaryCtaText: string;
  readonly secondaryCtaUrl: string;
  readonly aboutPreviewTitle: string;
  readonly aboutPreviewDescription: string;
  readonly aboutPreviewImageMediaId: number | null;
  readonly aboutPreviewCtaText: string;
  readonly aboutPreviewCtaUrl: string;
  readonly partnersSectionTitle: string;
  readonly partnersSectionDescription: string | null;
  readonly productsSectionTitle: string;
  readonly productsSectionDescription: string | null;
  readonly servicesSectionTitle: string;
  readonly servicesSectionDescription: string | null;
  readonly whyTitle: string;
  readonly whyDescription: string;
  readonly whyImageMediaId: number | null;
  readonly contactSectionTitle: string;
  readonly contactSectionDescription: string | null;
};

export type UpdateHomePageRepoInput = {
  readonly id: number;
  readonly heroTitle?: string;
  readonly heroDescription?: string;
  readonly heroImageMediaId?: number | null;
  readonly primaryCtaText?: string;
  readonly primaryCtaUrl?: string;
  readonly secondaryCtaText?: string;
  readonly secondaryCtaUrl?: string;
  readonly aboutPreviewTitle?: string;
  readonly aboutPreviewDescription?: string;
  readonly aboutPreviewImageMediaId?: number | null;
  readonly aboutPreviewCtaText?: string;
  readonly aboutPreviewCtaUrl?: string;
  readonly partnersSectionTitle?: string;
  readonly partnersSectionDescription?: string | null;
  readonly productsSectionTitle?: string;
  readonly productsSectionDescription?: string | null;
  readonly servicesSectionTitle?: string;
  readonly servicesSectionDescription?: string | null;
  readonly whyTitle?: string;
  readonly whyDescription?: string;
  readonly whyImageMediaId?: number | null;
  readonly contactSectionTitle?: string;
  readonly contactSectionDescription?: string | null;
};
