export type CreateHomePageRepoInput = {
  readonly heroTitle: string;
  readonly heroDescription: string;
  readonly heroImageMediaId: number | null;
  readonly primaryCtaText: string;
  readonly primaryCtaUrl: string;
  readonly secondaryCtaText: string;
  readonly secondaryCtaUrl: string;
  readonly aboutPreviewTitle: string;
  readonly aboutPreviewDescription: string;
  readonly aboutPreviewImageMediaId: number | null;
  readonly aboutPreviewCtaText: string;
  readonly aboutPreviewCtaUrl: string;
  readonly partnersSectionTitle: string;
  readonly partnersSectionDescription: string | null;
  readonly productsSectionTitle: string;
  readonly productsSectionDescription: string | null;
  readonly servicesSectionTitle: string;
  readonly servicesSectionDescription: string | null;
  readonly whyTitle: string;
  readonly whyDescription: string;
  readonly whyEyebrow: string;
  readonly whyReason1Title: string;
  readonly whyReason1Description: string;
  readonly whyReason2Title: string;
  readonly whyReason2Description: string;
  readonly whyReason3Title: string;
  readonly whyReason3Description: string;
  readonly whyReason4Title: string;
  readonly whyReason4Description: string;
  readonly whyImageMediaId: number | null;
  readonly heroEyebrow: string;
  readonly aboutEyebrow: string;
  readonly aboutMetric1Value: string;
  readonly aboutMetric1Label: string;
  readonly aboutMetric2Value: string;
  readonly aboutMetric2Label: string;
  readonly aboutMetric3Value: string;
  readonly aboutMetric3Label: string;
  readonly contactSectionTitle: string;
  readonly contactSectionDescription: string | null;
};

export type UpdateHomePageRepoInput = {
  readonly id: number;
  readonly heroTitle?: string;
  readonly heroDescription?: string;
  readonly heroImageMediaId?: number | null;
  readonly primaryCtaText?: string;
  readonly primaryCtaUrl?: string;
  readonly secondaryCtaText?: string;
  readonly secondaryCtaUrl?: string;
  readonly aboutPreviewTitle?: string;
  readonly aboutPreviewDescription?: string;
  readonly aboutPreviewImageMediaId?: number | null;
  readonly aboutPreviewCtaText?: string;
  readonly aboutPreviewCtaUrl?: string;
  readonly partnersSectionTitle?: string;
  readonly partnersSectionDescription?: string | null;
  readonly productsSectionTitle?: string;
  readonly productsSectionDescription?: string | null;
  readonly servicesSectionTitle?: string;
  readonly servicesSectionDescription?: string | null;
  readonly whyTitle?: string;
  readonly whyDescription?: string;
  readonly whyEyebrow?: string;
  readonly whyReason1Title?: string;
  readonly whyReason1Description?: string;
  readonly whyReason2Title?: string;
  readonly whyReason2Description?: string;
  readonly whyReason3Title?: string;
  readonly whyReason3Description?: string;
  readonly whyReason4Title?: string;
  readonly whyReason4Description?: string;
  readonly whyImageMediaId?: number | null;
  readonly heroEyebrow?: string;
  readonly aboutEyebrow?: string;
  readonly aboutMetric1Value?: string;
  readonly aboutMetric1Label?: string;
  readonly aboutMetric2Value?: string;
  readonly aboutMetric2Label?: string;
  readonly aboutMetric3Value?: string;
  readonly aboutMetric3Label?: string;
  readonly contactSectionTitle?: string;
  readonly contactSectionDescription?: string | null;
};
