export const CONTACT_INQUIRY_FULL_NAME_MAX_LENGTH = 200;
export const CONTACT_INQUIRY_EMAIL_MAX_LENGTH = 254;
export const CONTACT_INQUIRY_PHONE_MAX_LENGTH = 50;
export const CONTACT_INQUIRY_SUBJECT_MAX_LENGTH = 200;
export const CONTACT_INQUIRY_MESSAGE_MAX_LENGTH = 5000;
export const CONTACT_INQUIRY_EMAIL_SUBJECT_PREFIX = 'Contact form: ';
