export const appPaths = {
  home: '/',
  about: '/about',
  partners: '/partners',
  products: '/products',
  productDetail: '/products/:productId',
  services: '/services',
  contact: '/contact',
  adminLogin: '/admin/login',
  adminHome: '/admin',
  adminWebsiteHome: '/admin/home-page',
  adminWebsiteAbout: '/admin/about-page',
  adminWebsiteSettings: '/admin/settings',
  adminCatalogCategories: '/admin/categories',
  adminCatalogProducts: '/admin/products',
  adminCompanyPartners: '/admin/partners',
  adminCompanyServices: '/admin/services',
  adminContactLocations: '/admin/locations',
  adminContactInformation: '/admin/contact-information',
  adminContactSocial: '/admin/social-media',
} as const;
